"""add deals table

Revision ID: 179db162ad2d
Revises: 7aea5cb294f7
Create Date: 2026-03-02 22:11:58.634040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179db162ad2d'
down_revision = '7aea5cb294f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###