"""add agent_id to properties

Revision ID: 3c4a8437e3a9
Revises: aa93b177f836
Create Date: 2026-03-03 22:23:22.689413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4a8437e3a9'
down_revision = 'aa93b177f836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('agent_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_properties_agent_id'), 'properties', ['agent_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'users', ['agent_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_agent_id'), table_name='properties')
    op.drop_column('properties', 'agent_id')
    # ### end Alembic commands ###